use anyhow::Result;
use ce_store::Db;
use clap::ValueEnum;
use std::fs;
use std::path::Path;

#[derive(Clone, Copy, Debug, ValueEnum)]
pub enum ProjectTemplate {
    Web,
    Mobile,
    Rust,
}

#[derive(Clone, Copy, Debug, ValueEnum)]
pub enum ProjectSubtype {
    Cli,
}

/// Apply a template kit into the repo.
///
/// This writes:
/// - .prune/prune.preferences.json
/// - .prune/prune.decisions.md
/// - .prune/prune.intent_router.json
/// - .prune/prune.reference_sources.json
/// - .ce/strategies/{inception,failure_fix}.toml
///
/// If `force` is false, existing files are not overwritten.
pub fn apply_template(
    repo: &Path,
    template: ProjectTemplate,
    subtype: Option<ProjectSubtype>,
    force: bool,
) -> Result<()> {
    let prune_dir = repo.join(".prune");
    fs::create_dir_all(&prune_dir)?;
    let ce_strat_dir = repo.join(".ce").join("strategies");
    fs::create_dir_all(&ce_strat_dir)?;

    write_if_missing_or_force(
        &prune_dir.join("prune.preferences.json"),
        &default_preferences(template, subtype)?,
        force,
    )?;
    write_if_missing_or_force(
        &prune_dir.join("prune.decisions.md"),
        &default_decisions(template, subtype),
        force,
    )?;
    write_if_missing_or_force(
        &prune_dir.join("prune.intent_router.json"),
        &default_intent_router(),
        force,
    )?;
    write_if_missing_or_force(
        &prune_dir.join("prune.reference_sources.json"),
        &default_reference_sources(template),
        force,
    )?;

    write_if_missing_or_force(
        &ce_strat_dir.join("inception.toml"),
        &default_inception_strategy(template),
        force,
    )?;
    write_if_missing_or_force(
        &ce_strat_dir.join("failure_fix.toml"),
        &default_failure_strategy(template),
        force,
    )?;

    Ok(())
}

pub fn write_onboarding(repo: &Path, db: &Db, template: ProjectTemplate) -> Result<()> {
    let prune_dir = repo.join(".prune");
    fs::create_dir_all(&prune_dir)?;
    let out = prune_dir.join("prune.onboarding.md");

    let mut md = String::new();
    md.push_str("# Prune Onboarding\n\n");
    md.push_str("This file is generated by `ce bootstrap`.\n\n");
    md.push_str("## Repo entry points (template heuristics)\n\n");

    let mut candidates: Vec<&str> = match template {
        ProjectTemplate::Web => vec![
            "src/main.tsx",
            "src/App.tsx",
            "src/main.ts",
            "src/App.ts",
            "vite.config.ts",
            "tailwind.config.js",
            "tailwind.config.ts",
            "supabase/functions",
            "supabase/edge-functions",
        ],
        ProjectTemplate::Mobile => vec!["Package.swift"],
        ProjectTemplate::Rust => vec!["Cargo.toml", "src/main.rs", "src/lib.rs"],
    };

    // Include files that exist in the index (path match) when possible.
    let api_map = db.api_summary_map_all()?;
    let api_paths: Vec<String> = api_map.keys().cloned().collect();
    for c in candidates.drain(..) {
        let hit = api_paths.iter().find(|p| p.ends_with(c));
        if let Some(p) = hit {
            md.push_str(&format!("- `{}`\n", p));
        }
    }
    md.push_str("\n## Key API summaries (high-signal)\n\n");
    // Include a small selection of api summaries based on template.
    let mut chosen: Vec<String> = vec![];
    for p in &api_paths {
        match template {
            ProjectTemplate::Web => {
                if p.contains("src/")
                    && (p.contains("lib/")
                        || p.contains("hooks/")
                        || p.contains("components/")
                        || p.contains("supabase"))
                {
                    chosen.push(p.clone());
                }
            }
            ProjectTemplate::Mobile => {
                if p.ends_with(".swift")
                    && (p.contains("App")
                        || p.contains("View")
                        || p.contains("Model")
                        || p.contains("Service"))
                {
                    chosen.push(p.clone());
                }
            }
            ProjectTemplate::Rust => {
                if p.ends_with(".rs") && (p.contains("src/") || p.contains("crates/")) {
                    chosen.push(p.clone());
                }
            }
        }
        if chosen.len() >= 8 {
            break;
        }
    }

    if chosen.is_empty() {
        // fallback: first few api summaries
        chosen = api_paths.into_iter().take(8).collect();
    }

    for p in chosen {
        if let Some(rowid) = api_map.get(&p) {
            let frag = db.get_fragment_by_rowid(*rowid)?;
            md.push_str(&format!("### `{}`\n\n", p));
            md.push_str("```text\n");
            md.push_str(&frag.signature);
            md.push_str("\n```\n\n");
        }
    }

    fs::write(out, md)?;
    Ok(())
}

pub fn write_golden_paths(repo: &Path, db: &Db, template: ProjectTemplate) -> Result<()> {
    let prune_dir = repo.join(".prune");
    fs::create_dir_all(&prune_dir)?;
    let out = prune_dir.join("prune.golden_paths.json");

    let api_map = db.api_summary_map_all()?;
    let paths: Vec<String> = api_map.keys().cloned().collect();

    let mut picks: Vec<String> = Vec::new();

    // Entry points
    let entry_candidates: Vec<&str> = match template {
        ProjectTemplate::Web => vec!["src/main.tsx", "src/App.tsx", "src/main.ts", "src/App.ts"],
        ProjectTemplate::Mobile => vec!["App.swift", "ContentView.swift"],
        ProjectTemplate::Rust => vec!["src/main.rs", "src/lib.rs"],
    };
    for c in entry_candidates {
        if let Some(p) = paths.iter().find(|p| p.ends_with(c)) {
            picks.push(p.clone());
        }
    }

    // Supabase hub for web
    if matches!(template, ProjectTemplate::Web) {
        for p in &paths {
            if p.contains("supabase") && (p.contains("client") || p.contains("supabase")) {
                picks.push(p.clone());
                if picks.len() >= 8 {
                    break;
                }
            }
        }
    }

    // Fill remaining with a few representative paths
    for p in &paths {
        if picks.len() >= 12 {
            break;
        }
        if !picks.contains(p) {
            // prefer src/ and non-test
            if p.contains("src/") && !p.contains("test") && !p.contains("__tests__") {
                picks.push(p.clone());
            }
        }
    }
    if picks.is_empty() {
        picks = paths.into_iter().take(10).collect();
    }

    let payload = serde_json::json!({
        "version": 1,
        "template": format!("{:?}", template),
        "generated_at": format!("{}", std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_secs()),
        "paths": picks
    });
    fs::write(out, serde_json::to_string_pretty(&payload)?)?;
    Ok(())
}

fn write_if_missing_or_force(path: &Path, content: &str, force: bool) -> Result<()> {
    if path.exists() && !force {
        return Ok(());
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, content)?;
    Ok(())
}

fn default_preferences(
    template: ProjectTemplate,
    subtype: Option<ProjectSubtype>,
) -> Result<String> {
    let (project_type, stack, thin_slice) = match template {
        ProjectTemplate::Web => (
            "web",
            vec![
                "react",
                "vite",
                "tailwind",
                "supabase",
                "supabase_edge_functions",
            ],
            "A minimal working UI flow + one data call with basic error handling.",
        ),
        ProjectTemplate::Mobile => (
            "mobile",
            vec!["swiftui", "swift6", "xcode_multiplatform"],
            "One screen end-to-end with navigation + a data stub + error state.",
        ),
        ProjectTemplate::Rust => (
            "rust",
            vec!["rust"],
            "A small end-to-end command or API surface with one test.",
        ),
    };

    let subtype_val = subtype.map(|s| format!("{:?}", s));
    let json = serde_json::json!({
        "version": 1,
        "project_type": project_type,
        "subtype": subtype_val,
        "stack": stack,
        "answers": {
            "scope": { "thinSliceDefinition": thin_slice },
            "types": { "strictness": "balanced" },
            "testing": { "requiredForFeatures": true, "preferred": ["unit","integration"] },
            "deps": { "newDependencyPolicy": "avoid_unless_clear_win" },
            "workflow": { "smallPRsPreferred": true, "commitStyle": "concise" }
        }
    });
    Ok(serde_json::to_string_pretty(&json)?)
}

fn default_decisions(template: ProjectTemplate, subtype: Option<ProjectSubtype>) -> String {
    let mut s = String::new();
    s.push_str("# Prune Decisions\n\n");
    s.push_str("This file can be edited. It is initially created by `ce bootstrap`.\n\n");
    match template {
        ProjectTemplate::Web => {
            s.push_str("- Prefer small, composable modules and thin slices.\n");
            s.push_str("- Keep UI structure lightweight; focus on logic and data flow.\n");
            s.push_str("- Treat Supabase client usage as a shared hub.\n");
        }
        ProjectTemplate::Mobile => {
            s.push_str("- Prefer SwiftUI-first patterns and incremental feature slices.\n");
            s.push_str("- Keep View bodies small; move logic into view models/services.\n");
        }
        ProjectTemplate::Rust => {
            s.push_str("- Prefer clear module boundaries and explicit error handling.\n");
            s.push_str("- Use tests for new functionality.\n");
        }
    }
    if let Some(ProjectSubtype::Cli) = subtype {
        s.push_str("- CLI subtype: prefer clear subcommands, good error messages, and stable exit codes.\n");
    }
    s
}

fn default_intent_router() -> String {
    // Intent router used by PruneApp / agents to select strategy profile.
    let json = serde_json::json!({
        "version": 1,
        "router": [
            {"intent": "inception", "strategy": ".ce/strategies/inception.toml"},
            {"intent": "fix_failure", "strategy": ".ce/strategies/failure_fix.toml"},
            {"intent": "refactor", "strategy": ".ce/strategies/inception.toml"}
        ]
    });
    serde_json::to_string_pretty(&json).unwrap()
}

fn default_reference_sources(template: ProjectTemplate) -> String {
    // Only pointers; do not download anything in bootstrap.
    let sources = match template {
        ProjectTemplate::Web => vec![
            serde_json::json!({"name":"React","type":"official","url":"https://react.dev/"}),
            serde_json::json!({"name":"Vite","type":"official","url":"https://vitejs.dev/"}),
            serde_json::json!({"name":"Tailwind","type":"official","url":"https://tailwindcss.com/docs"}),
            serde_json::json!({"name":"Supabase","type":"official","url":"https://supabase.com/docs"}),
        ],
        ProjectTemplate::Mobile => vec![
            serde_json::json!({"name":"SwiftUI","type":"official","url":"https://developer.apple.com/documentation/swiftui"}),
            serde_json::json!({"name":"Swift","type":"official","url":"https://developer.apple.com/documentation/swift"}),
        ],
        ProjectTemplate::Rust => vec![
            serde_json::json!({"name":"Rust Book","type":"official","url":"https://doc.rust-lang.org/book/"}),
            serde_json::json!({"name":"Rust Std","type":"official","url":"https://doc.rust-lang.org/std/"}),
        ],
    };
    serde_json::to_string_pretty(&serde_json::json!({"version":1,"sources":sources})).unwrap()
}

fn default_inception_strategy(_template: ProjectTemplate) -> String {
    // Keep it conservative and small: signatures first, minimal bodies.
    r#"
# Prune inception strategy (template default)
mode = "signatures_first"
candidate_pool_limit = 200
lexical_k = 40
semantic_k = 40
edge_radius = 2
edge_include_outgoing = true
edge_include_incoming = false
max_bodies = 1
avoid_seen = true
"#
    .trim()
    .to_string()
}

fn default_failure_strategy(_template: ProjectTemplate) -> String {
    r#"
# Prune failure-fix strategy (template default)
mode = "signals_first"
signals_enabled = true
candidate_pool_limit = 240
lexical_k = 60
semantic_k = 50
edge_radius = 3
edge_include_outgoing = true
edge_include_incoming = true
max_bodies = 2
avoid_seen = true
"#
    .trim()
    .to_string()
}
