use anyhow::Result;
use ce_core::model::{FragKind, Fragment, Span, StrategyConfig};
use ce_core::slicing::{select_ast_nodes, AstNodeRole, AstNodeSpan, AstSlice, AstSliceRequest};
use ce_core::util::{hash_text_hex, normalize_whitespace};
use std::collections::{HashMap, HashSet};
use std::path::{Path, PathBuf};
use tree_sitter::{Node, Parser, Tree};

pub struct RustAdapter {
    parser: Parser,
}

/// Apply the shared AST slicing policy using Rust grammar nodes.
pub fn policy_ast_slice(request: AstSliceRequest<'_>) -> Result<Option<AstSlice>> {
    let mut parser = Parser::new();
    parser.set_language(&tree_sitter_rust::LANGUAGE.into())?;
    let Some(tree) = parser.parse(request.source, None) else {
        return Ok(None);
    };
    let nodes = collect_policy_nodes(
        tree.root_node(),
        request.source.as_bytes(),
        0,
        rust_node_role,
    );
    Ok(select_ast_nodes(&request, &nodes))
}

fn rust_node_role(kind: &str) -> Option<AstNodeRole> {
    if kind.contains("comment") {
        return Some(AstNodeRole::Documentation);
    }
    if matches!(
        kind,
        "struct_item" | "enum_item" | "trait_item" | "type_item"
    ) {
        return Some(AstNodeRole::TypeDeclaration);
    }
    if matches!(
        kind,
        "function_item" | "impl_item" | "mod_item" | "const_item" | "static_item"
    ) {
        return Some(AstNodeRole::Declaration);
    }
    if kind == "call_expression" || kind == "macro_invocation" {
        return Some(AstNodeRole::CallSite);
    }
    if matches!(
        kind,
        "if_expression"
            | "match_expression"
            | "match_arm"
            | "while_expression"
            | "for_expression"
            | "loop_expression"
    ) {
        return Some(AstNodeRole::Branch);
    }
    if matches!(kind, "block" | "expression_statement" | "let_declaration") {
        return Some(AstNodeRole::Body);
    }
    None
}

fn collect_policy_nodes(
    node: Node<'_>,
    bytes: &[u8],
    depth: usize,
    classify: fn(&str) -> Option<AstNodeRole>,
) -> Vec<AstNodeSpan> {
    let mut out = Vec::new();
    if let Some(role) = classify(node.kind()) {
        let end_line = if matches!(
            role,
            AstNodeRole::Declaration | AstNodeRole::TypeDeclaration
        ) {
            node.start_position().row
        } else {
            node.end_position().row
        };
        out.push(AstNodeSpan {
            start_line: node.start_position().row,
            end_line,
            depth,
            role,
            relevance_text: node.utf8_text(bytes).unwrap_or_default().to_string(),
        });
    }
    let mut cursor = node.walk();
    for child in node.named_children(&mut cursor) {
        out.extend(collect_policy_nodes(child, bytes, depth + 1, classify));
    }
    out
}

#[cfg(test)]
mod policy_slice_tests {
    use super::*;
    use ce_core::model::AstSlicePolicy;

    #[test]
    fn shared_policy_keeps_rust_signature_and_referenced_branch() {
        let source =
            "fn run() {\n    if needle() {\n        selected();\n    }\n    ignored();\n}\n";
        let focus = vec!["needle".to_string()];
        let policy = AstSlicePolicy::default();
        let slice = policy_ast_slice(AstSliceRequest {
            source,
            fragment_start_line: 0,
            target_lines: &[],
            focus_symbols: &focus,
            policy: &policy,
        })
        .unwrap()
        .unwrap();
        assert!(slice.text.contains("fn run"));
        assert!(slice.text.contains("if needle"));
        assert!(!slice.text.contains("ignored"));
    }
}

/// Collect some file-level identifier references from `use`/`pub use` and
/// `mod`/`pub mod` lines.
///
/// These refs are useful for graph-ish expansion even when the `use` statement
/// itself is not selected as a fragment. We attach them to a file-level
/// `ApiSummary` fragment (generated by `ce-core` at index time).
pub fn collect_file_level_refs(source: &str) -> Vec<String> {
    let mut out: HashSet<String> = HashSet::new();

    for raw in source.lines() {
        let mut line = raw.trim();
        if line.is_empty() {
            continue;
        }

        // Strip single-line comments.
        if let Some((before, _)) = line.split_once("//") {
            line = before.trim();
        }
        if line.is_empty() {
            continue;
        }

        // `use ...;` or `pub use ...;`
        if line.starts_with("use ") || line.starts_with("pub use ") {
            parse_use_like_line(line, &mut out);
            continue;
        }

        // `mod foo;` or `pub mod foo;`
        if line.starts_with("mod ") || line.starts_with("pub mod ") {
            let mut s = line.trim_end_matches(';').trim();
            if let Some(rest) = s.strip_prefix("pub ") {
                s = rest.trim();
            }
            if let Some(rest) = s.strip_prefix("mod ") {
                let rest = rest.trim();
                let ident = rest
                    .split(|c: char| !(c.is_ascii_alphanumeric() || c == '_'))
                    .next()
                    .unwrap_or("")
                    .trim();
                if !ident.is_empty() {
                    out.insert(ident.to_string());
                }
            }
            continue;
        }
    }

    let mut v: Vec<String> = out.into_iter().collect();
    v.sort();
    v.truncate(128);
    v
}

fn parse_use_like_line(line: &str, out: &mut HashSet<String>) {
    let mut s = line.trim();
    s = s.trim_end_matches(';').trim();
    if let Some(rest) = s.strip_prefix("pub ") {
        s = rest.trim();
    }
    let Some(rest) = s.strip_prefix("use ") else {
        return;
    };
    s = rest.trim();

    // Remove common roots.
    while let Some(rest) = s
        .strip_prefix("crate::")
        .or_else(|| s.strip_prefix("self::"))
        .or_else(|| s.strip_prefix("super::"))
    {
        s = rest;
    }

    // Handle grouped imports: `foo::{A, B as C}`
    if let Some(brace) = s.find('{') {
        let prefix = s[..brace].trim().trim_end_matches("::").trim();
        let inside = s[brace..].trim();
        let inside = inside.trim_start_matches('{').trim_end_matches('}').trim();

        for part in inside.split(',') {
            let part = part.trim();
            if part.is_empty() {
                continue;
            }
            if part == "self" {
                if let Some(last) = prefix.split("::").filter(|t| !t.is_empty()).last() {
                    if last != "*" {
                        out.insert(last.to_string());
                    }
                }
                continue;
            }

            if let Some((lhs, rhs)) = part.split_once(" as ") {
                let lhs_last = lhs
                    .trim()
                    .split("::")
                    .filter(|t| !t.is_empty())
                    .last()
                    .unwrap_or("");
                let rhs_last = rhs
                    .trim()
                    .split("::")
                    .filter(|t| !t.is_empty())
                    .last()
                    .unwrap_or("");
                if !lhs_last.is_empty() && lhs_last != "*" {
                    out.insert(lhs_last.to_string());
                }
                if !rhs_last.is_empty() && rhs_last != "*" {
                    out.insert(rhs_last.to_string());
                }
                continue;
            }

            let last = part
                .split("::")
                .filter(|t| !t.is_empty())
                .last()
                .unwrap_or("")
                .trim();
            if !last.is_empty() && last != "*" {
                out.insert(last.to_string());
            }
        }
        return;
    }

    // Non-grouped import.
    if let Some((lhs, rhs)) = s.split_once(" as ") {
        let lhs_last = lhs
            .trim()
            .split("::")
            .filter(|t| !t.is_empty())
            .last()
            .unwrap_or("");
        let rhs_last = rhs
            .trim()
            .split("::")
            .filter(|t| !t.is_empty())
            .last()
            .unwrap_or("");
        if !lhs_last.is_empty() && lhs_last != "*" {
            out.insert(lhs_last.to_string());
        }
        if !rhs_last.is_empty() && rhs_last != "*" {
            out.insert(rhs_last.to_string());
        }
        return;
    }

    let last = s
        .split("::")
        .filter(|t| !t.is_empty())
        .last()
        .unwrap_or("")
        .trim();
    if !last.is_empty() && last != "*" {
        out.insert(last.to_string());
    }
}

impl RustAdapter {
    pub fn new() -> Result<Self> {
        let mut parser = Parser::new();
        parser.set_language(&tree_sitter_rust::LANGUAGE.into())?;
        Ok(Self { parser })
    }

    pub fn parse(&mut self, source: &str) -> Result<Tree> {
        self.parser
            .parse(source, None)
            .ok_or_else(|| anyhow::anyhow!("tree-sitter parse returned None"))
    }

    /// Extract fragments from a Rust source file.
    ///
    /// MVP behavior:
    /// - extracts top-level items (fn/struct/enum/trait/impl/mod/const/static/type)
    /// - also extracts methods inside impl blocks as separate fragments (granularity)
    ///
    /// Note: file-level API summaries are generated in a language-agnostic way
    /// by `ce-core::api_summary` at index time.
    pub fn extract_fragments(&self, path: &Path, source: &str, tree: &Tree) -> Vec<Fragment> {
        let root = tree.root_node();
        let bytes = source.as_bytes();

        let mut out: Vec<Fragment> = Vec::new();
        let mut cursor = root.walk();

        for item in root.named_children(&mut cursor) {
            // skip non-items
            if let Some(mut frags) = self.fragments_from_item(path, bytes, item) {
                out.append(&mut frags);
            }
        }

        out
    }

    fn fragments_from_item(&self, path: &Path, bytes: &[u8], node: Node) -> Option<Vec<Fragment>> {
        let mut out: Vec<Fragment> = Vec::new();

        // Top-level item
        if let Some(f) = self.fragment_from_node(path, bytes, node, None, None) {
            // If it's an impl, also extract methods inside
            if f.kind == FragKind::Impl {
                let impl_type = self
                    .impl_target_type(bytes, node)
                    .unwrap_or_else(|| "impl".to_string());
                out.push(f.clone());

                // Methods inside impl are usually function_item nodes under declaration_list
                let mut cursor = node.walk();
                for ch in node.named_children(&mut cursor) {
                    self.collect_impl_methods(path, bytes, ch, &impl_type, &mut out);
                }
                return Some(out);
            }

            out.push(f);
            return Some(out);
        }

        None
    }

    fn collect_impl_methods(
        &self,
        path: &Path,
        bytes: &[u8],
        node: Node,
        impl_type: &str,
        out: &mut Vec<Fragment>,
    ) {
        // Walk impl subtree and extract function_item nodes nested within.
        let mut cursor = node.walk();
        if node.kind() == "function_item" {
            // Heuristic: only treat direct declaration_list children as impl methods.
            if node.parent().map(|p| p.kind()) == Some("declaration_list") {
                if let Some(f) = self.fragment_from_node(
                    path,
                    bytes,
                    node,
                    Some(FragKind::Method),
                    Some(impl_type),
                ) {
                    out.push(f);
                }
            }
            return;
        }
        for ch in node.named_children(&mut cursor) {
            self.collect_impl_methods(path, bytes, ch, impl_type, out);
        }
    }

    fn fragment_from_node(
        &self,
        path: &Path,
        bytes: &[u8],
        node: Node,
        force_kind: Option<FragKind>,
        method_impl_type: Option<&str>,
    ) -> Option<Fragment> {
        let preamble = extract_preamble(bytes, node.start_byte());

        let (mut kind, mut symbol) = match node.kind() {
            "function_item" => (FragKind::Function, self.node_name(bytes, node)),
            "struct_item" => (FragKind::Struct, self.node_name(bytes, node)),
            "enum_item" => (FragKind::Enum, self.node_name(bytes, node)),
            "trait_item" => (FragKind::Trait, self.node_name(bytes, node)),
            "impl_item" => (FragKind::Impl, self.impl_name(bytes, node)),
            "mod_item" => (FragKind::Mod, self.node_name(bytes, node)),
            "const_item" => (FragKind::Const, self.node_name(bytes, node)),
            "static_item" => (FragKind::Static, self.node_name(bytes, node)),
            "type_item" => (FragKind::TypeAlias, self.node_name(bytes, node)),
            _ => return None,
        };

        // Apply forced kind (e.g. impl methods)
        if let Some(fk) = force_kind {
            kind = fk;
        }

        // Best-effort: mark test functions
        if kind == FragKind::Function && is_test_preamble(&preamble) {
            kind = FragKind::Test;
        }

        // If this is a method and we have an impl type, qualify the symbol.
        if kind == FragKind::Method {
            if let (Some(impl_ty), Some(name)) = (method_impl_type, symbol.as_deref()) {
                symbol = Some(format!("{}::{}", impl_ty.trim(), name.trim()));
            }
        }

        let span = Span {
            start_byte: node.start_byte(),
            end_byte: node.end_byte(),
            start_line: node.start_position().row as u32,
            start_col: node.start_position().column as u32,
            end_line: node.end_position().row as u32,
            end_col: node.end_position().column as u32,
        };

        let body = self
            .slice_utf8(bytes, span.start_byte, span.end_byte)
            .to_string();

        // Preamble lines (doc + attributes) immediately above the node.
        // We include these in the signature to preserve important context like `#[test]`.
        let signature_core = signature_from_body(&body);
        let signature = if preamble.is_empty() {
            signature_core
        } else {
            format!("{}\n{}", preamble, signature_core)
        };

        // Doc comments only (stored separately)
        let doc = preamble
            .lines()
            .filter(|l| l.trim_start().starts_with("///") || l.trim_start().starts_with("//!"))
            .collect::<Vec<_>>()
            .join("\n");

        // Unison-ish ids:
        // - content hash: normalized body
        // - ast hash: structural (sexp)
        let content_hash = hash_text_hex(&normalize_whitespace(&body));
        let ast_hash = hash_text_hex(&node.to_sexp());

        // retrieval text should be compact and semantic
        let retrieval_text = format!(
            "path: {}\nkind: {:?}\nsymbol: {}\n{}\n{}",
            path.display(),
            kind,
            symbol.clone().unwrap_or_default(),
            if doc.is_empty() {
                preamble.clone()
            } else {
                doc.clone()
            },
            signature
        );

        let refs = collect_identifiers(bytes, node);

        Some(Fragment {
            id: content_hash,
            ast_hash,
            file: PathBuf::from(path),
            kind,
            symbol,
            span,
            signature,
            body,
            doc,
            retrieval_text,
            refs,
        })
    }

    fn node_name(&self, bytes: &[u8], node: Node) -> Option<String> {
        if let Some(n) = node.child_by_field_name("name") {
            return n.utf8_text(bytes).ok().map(|s| s.to_string());
        }
        // fallback: scan for identifier
        let mut c = node.walk();
        for ch in node.named_children(&mut c) {
            match ch.kind() {
                "identifier" | "type_identifier" => {
                    return ch.utf8_text(bytes).ok().map(|s| s.to_string())
                }
                _ => {}
            }
        }
        None
    }

    fn impl_name(&self, bytes: &[u8], node: Node) -> Option<String> {
        // best-effort: first line of impl block
        let text = node.utf8_text(bytes).ok()?;
        Some(text.lines().next().unwrap_or("impl").trim().to_string())
    }

    fn impl_target_type(&self, bytes: &[u8], node: Node) -> Option<String> {
        // Best-effort extraction of the impl target type.
        // tree-sitter-rust names the field "type" for impl_item.
        if let Some(ty) = node.child_by_field_name("type") {
            return ty.utf8_text(bytes).ok().map(|s| s.trim().to_string());
        }
        // Fallback: parse from first line of `impl`.
        let first = self.impl_name(bytes, node)?;
        // e.g. "impl Foo" or "impl Trait for Foo" -> try to take last token
        let toks: Vec<&str> = first.split_whitespace().collect();
        toks.last().map(|s| s.to_string())
    }

    fn slice_utf8<'a>(&self, bytes: &'a [u8], start: usize, end: usize) -> &'a str {
        std::str::from_utf8(&bytes[start..end]).unwrap_or("")
    }
}

/// Extract contiguous preamble lines immediately above a start byte.
///
/// We include both doc comments and attributes because they can contain
/// important semantic information for an agent (e.g. `#[test]`, `#[cfg]`, `#[inline]`).
fn extract_preamble(bytes: &[u8], start_byte: usize) -> String {
    let s = std::str::from_utf8(bytes).unwrap_or("");
    let prefix = &s[..start_byte.min(s.len())];
    let mut lines: Vec<&str> = prefix.lines().collect();
    let mut keep: Vec<String> = Vec::new();
    let mut started = false;

    while let Some(line) = lines.pop() {
        let trimmed = line.trim_start();
        if trimmed.is_empty() {
            if started {
                break;
            }
            continue;
        }
        if trimmed.starts_with("///") || trimmed.starts_with("//!") || trimmed.starts_with("#[") {
            started = true;
            keep.push(trimmed.to_string());
            continue;
        }
        break;
    }

    keep.reverse();
    keep.join("\n")
}

fn is_test_preamble(preamble: &str) -> bool {
    let lower = preamble.to_ascii_lowercase();
    // Try to avoid matching `#[cfg(test)]` on modules by requiring the attribute
    // name to end with `test` (common forms)
    lower.contains("#[test]")
        || lower.contains("#[tokio::test")
        || lower.contains("#[async_std::test")
        || lower.contains("::test")
}

/// Signature heuristic: take up to N lines or until '{' or ';'.
fn signature_from_body(body: &str) -> String {
    let mut sig = String::new();
    for (i, line) in body.lines().enumerate() {
        sig.push_str(line);
        sig.push('\n');
        if line.contains('{') || line.contains(';') || i >= 20 {
            break;
        }
    }
    sig
}

/// Collect identifiers inside a node subtree (best-effort, cheap).
fn collect_identifiers(bytes: &[u8], node: Node) -> Vec<String> {
    let mut out = HashSet::new();
    let mut cursor = node.walk();
    collect_identifiers_rec(bytes, node, &mut cursor, &mut out);
    let mut v: Vec<String> = out.into_iter().collect();
    v.sort();
    v
}

fn collect_identifiers_rec(
    bytes: &[u8],
    node: Node,
    cursor: &mut tree_sitter::TreeCursor,
    out: &mut HashSet<String>,
) {
    let kind = node.kind();
    if matches!(
        kind,
        "identifier"
            | "type_identifier"
            | "scoped_identifier"
            | "scoped_type_identifier"
            | "field_identifier"
    ) {
        if let Ok(t) = node.utf8_text(bytes) {
            let t = t.trim();
            if !t.is_empty() && t.len() <= 128 {
                // Always store the full token.
                out.insert(t.to_string());

                // For scoped paths like `foo::Bar`, also store the tail segment (`Bar`).
                // This makes ref→def resolution and incremental edge rebuilds more robust,
                // because definitions are often stored under the unqualified name.
                if matches!(kind, "scoped_identifier" | "scoped_type_identifier") {
                    if let Some(tail) = t.rsplit("::").next() {
                        let tail = tail.trim();
                        if !tail.is_empty() && tail.len() <= 128 && tail != t {
                            out.insert(tail.to_string());
                        }
                    }
                }
            }
        }
    }
    // Recurse
    if node.child_count() == 0 {
        return;
    }
    let mut c = node.walk();
    for ch in node.named_children(&mut c) {
        collect_identifiers_rec(bytes, ch, cursor, out);
    }
}

// -----------------------------------------------------------------------------
// AST-based body pruning (Rust)
// -----------------------------------------------------------------------------

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct Win {
    start: usize,
    end: usize,
}

fn leading_ws(s: &str) -> &str {
    let mut n = 0usize;
    for (i, ch) in s.char_indices() {
        if ch == ' ' || ch == '\t' {
            n = i + ch.len_utf8();
        } else {
            break;
        }
    }
    &s[..n]
}

/// Produce a compact slice of `body` by selecting AST-aligned windows.
///
/// This is more aggressive than simple line windows because it tries to:
/// - lock onto statement boundaries (rather than arbitrary line offsets)
/// - include control-flow headers for matched statements (e.g. `if`, `match`)
/// - keep output bounded by `max_lines`
///
/// Inputs:
/// - `frag_start_line0`: 0-based line in the *file* where this fragment starts.
/// - `targets_1based`: optional file line numbers to focus (signals).
/// - `match_tokens_lower`: lowercase identifier tokens to focus (symbols/task tokens).
pub fn ast_prune_slice(
    body: &str,
    frag_start_line0: u32,
    targets_1based: &[u32],
    match_tokens_lower: &[String],
    ctx_lines: usize,
    max_lines: usize,
) -> Option<String> {
    if max_lines == 0 {
        return None;
    }

    let lines: Vec<&str> = body.lines().collect();
    if lines.is_empty() {
        return None;
    }

    // If there is no signal and no match tokens, we can't focus anything.
    if targets_1based.is_empty() && match_tokens_lower.is_empty() {
        return None;
    }

    // Avoid work for tiny fragments.
    if lines.len() <= (max_lines.saturating_add(8)).max(32) {
        return None;
    }

    let mut parser = Parser::new();
    parser
        .set_language(&tree_sitter_rust::LANGUAGE.into())
        .ok()?;
    let tree = parser.parse(body, None)?;
    let root = tree.root_node();
    let bytes = body.as_bytes();

    let mut focus: HashSet<String> = HashSet::new();
    // Bound token set to keep traversal cheap.
    for t in match_tokens_lower.iter().take(64) {
        let tt = t.trim();
        if tt.len() >= 2 && tt.len() <= 64 {
            focus.insert(tt.to_string());
        }
    }

    let mut wins: Vec<Win> = Vec::new();

    // A) Signal-based points.
    for &line1 in targets_1based.iter().take(24) {
        let line0_file = line1.saturating_sub(1);
        if line0_file < frag_start_line0 {
            continue;
        }
        let rel0 = (line0_file - frag_start_line0) as usize;
        if rel0 >= lines.len() {
            continue;
        }

        let stmt = statement_for_line(&root, rel0)?;
        push_windows_for_match(&mut wins, &stmt, rel0, ctx_lines, lines.len());
    }

    // B) Identifier/token matches.
    if !focus.is_empty() {
        let mut added = 0usize;
        let mut cursor = root.walk();
        collect_token_windows(
            bytes,
            &focus,
            root,
            &mut cursor,
            &mut wins,
            ctx_lines,
            lines.len(),
            &mut added,
        );
    }

    if wins.is_empty() {
        return None;
    }

    // Merge / sort.
    wins.sort_by_key(|w| (w.start, w.end));
    let mut merged: Vec<Win> = Vec::new();
    for w in wins {
        if let Some(last) = merged.last_mut() {
            if w.start <= last.end.saturating_add(1) {
                last.end = last.end.max(w.end);
                continue;
            }
        }
        merged.push(w);
    }

    // Render with file line numbers.
    let mut out = String::new();
    let mut written = 0usize;
    let mut prev_end: Option<usize> = None;

    // Indent-aware placeholders when skipping between windows.
    let indent_size: usize = 4;
    let gap_indent = |prev: &str, next: &str| -> String {
        let p = prev.trim_end();
        let n = next.trim_start();
        let ip = leading_ws(prev).to_string();
        let inext = leading_ws(next).to_string();
        if p.ends_with('{') && n.starts_with('}') {
            let mut s = String::new();
            s.push_str(&ip);
            s.push_str(&" ".repeat(indent_size));
            return s;
        }
        if inext.len() > ip.len() {
            inext
        } else {
            ip
        }
    };

    for w in merged {
        if written >= max_lines {
            break;
        }
        if let Some(pe) = prev_end {
            if w.start > pe.saturating_add(1) {
                let prev_line = lines.get(pe).copied().unwrap_or("");
                let next_line = lines.get(w.start).copied().unwrap_or("");
                let ind = gap_indent(prev_line, next_line);
                out.push_str(&format!("{}...\n", ind));
                written += 1;
                if written >= max_lines {
                    return Some(out);
                }
            }
        }
        let start = w.start.min(lines.len().saturating_sub(1));
        let end = w.end.min(lines.len().saturating_sub(1));
        for i in start..=end {
            if written >= max_lines {
                let prev_line = lines.get(i.saturating_sub(1)).copied().unwrap_or("");
                let next_line = lines.get(i).copied().unwrap_or("");
                let ind = gap_indent(prev_line, next_line);
                out.push_str(&format!("{}...\n", ind));
                return Some(out);
            }
            let file_line_1based = frag_start_line0 as usize + i + 1;
            out.push_str(&format!("L{:>5}: {}\n", file_line_1based, lines[i]));
            written += 1;
        }
        prev_end = Some(end);
    }

    if out.trim().is_empty() {
        None
    } else {
        Some(out)
    }
}

/// Produce a compact "skeleton" slice of `body` by keeping only structural lines.
///
/// Compared to `ast_prune_slice`, this is intentionally *more aggressive*:
/// it tries to preserve the **shape** of large fragments while omitting deep subtrees.
///
/// Heuristics (Rust):
/// - keep control-flow headers (`if`, `for`, `while`, `match`, `loop`)
/// - keep `match` arm headers (bounded)
/// - keep `impl` method signature lines (bounded)
/// - collapse large literals (arrays) to head/tail
///
/// Output format matches other slices: line-numbered with `...` gaps.
pub fn ast_skeleton_slice(
    body: &str,
    frag_start_line0: u32,
    frag_kind: FragKind,
    targets_1based: &[u32],
    match_tokens_lower: &[String],
    cfg: &StrategyConfig,
) -> Option<String> {
    let max_lines = cfg.body_snippet_max_lines;
    if max_lines == 0 {
        return None;
    }

    let lines: Vec<&str> = body.lines().collect();
    if lines.is_empty() {
        return None;
    }

    // Only worth doing on larger bodies or for kinds where skeletonization is especially useful.
    let big_enough = lines.len() >= cfg.ast_skeleton_large_literal_line_threshold.max(12);
    if !big_enough
        && !matches!(
            frag_kind,
            FragKind::Impl | FragKind::Const | FragKind::Static
        )
    {
        return None;
    }

    let mut parser = Parser::new();
    parser
        .set_language(&tree_sitter_rust::LANGUAGE.into())
        .ok()?;
    let tree = parser.parse(body, None)?;
    let root = tree.root_node();
    let bytes = body.as_bytes();
    let line_cap = lines.len();

    // Avoid repeating the signature lines already included in `decorate_slice`.
    let sig_lines = signature_from_body(body).lines().count();
    let skip = sig_lines.min(line_cap);

    let mut line_prio: HashMap<usize, u16> = HashMap::new();
    let mut add_line = |idx: usize, prio: u16| {
        if idx < skip || idx >= line_cap {
            return;
        }
        let e = line_prio.entry(idx).or_insert(0);
        if prio > *e {
            *e = prio;
        }
    };

    // Always include fragment end line (often `}` / `};`).
    if line_cap >= 2 {
        add_line(line_cap.saturating_sub(1), 10);
    }

    // A) Signals: ensure the target line + its statement container boundaries.
    for &line1 in targets_1based.iter().take(24) {
        if line1 == 0 {
            continue;
        }
        let line0_file = line1.saturating_sub(1);
        if line0_file < frag_start_line0 {
            continue;
        }
        let rel0 = (line0_file - frag_start_line0) as usize;
        if rel0 >= line_cap {
            continue;
        }
        add_line(rel0, 250);
        if let Some(stmt) = statement_for_line(&root, rel0) {
            let (s, e) = node_line_span(&stmt, line_cap);
            add_line(s, 240);
            add_line(e, 230);
        }
    }

    // B) Token matches: pick statement containers for identifier nodes that match focus tokens.
    if !match_tokens_lower.is_empty() {
        let mut focus: HashSet<String> = HashSet::new();
        for t in match_tokens_lower.iter().take(64) {
            let tt = t.trim();
            if tt.len() >= 2 && tt.len() <= 64 {
                focus.insert(tt.to_string());
            }
        }
        if !focus.is_empty() {
            let mut added = 0usize;
            let mut cursor = root.walk();
            collect_skeleton_token_picks(
                bytes,
                &focus,
                root,
                &mut cursor,
                &mut add_line,
                &mut added,
                line_cap,
            );
        }
    }

    // C) Kind-specific: impl method signatures.
    if frag_kind == FragKind::Impl {
        // Add impl header/footer if present.
        if let Some(impl_node) = find_first_kind(root, "impl_item") {
            let (s, e) = node_line_span(&impl_node, line_cap);
            add_line(s, 190);
            add_line(e, 180);
        }

        let mut n = 0usize;
        let mut cursor = root.walk();
        for ch in root.named_children(&mut cursor) {
            collect_impl_method_skeleton_lines_rec(
                ch,
                &mut add_line,
                cfg.ast_skeleton_impl_method_limit,
                &mut n,
            );
            if n >= cfg.ast_skeleton_impl_method_limit {
                break;
            }
        }
    }

    // D) Large literals (arrays) head/tail.
    let mut lit_budget = 0usize;
    collect_large_literal_skeleton_lines(&root, 0, cfg, &mut add_line, &mut lit_budget, line_cap);

    // E) General control-flow / match skeleton.
    let mut node_budget = cfg.ast_skeleton_max_nodes.max(16);
    collect_control_flow_skeleton_lines(&root, 0, cfg, &mut add_line, &mut node_budget, line_cap);

    if line_prio.is_empty() {
        return None;
    }

    // Select high-priority lines first, but render in source order.
    let mut picks: Vec<(usize, u16)> = line_prio.into_iter().collect();
    picks.sort_by(|a, b| b.1.cmp(&a.1).then(a.0.cmp(&b.0)));

    // Keep some slack for `...` lines inserted between groups.
    let keep_n = (max_lines.saturating_mul(2))
        .max(max_lines)
        .min(picks.len());
    picks.truncate(keep_n);

    let mut idxs: Vec<usize> = picks.into_iter().map(|(i, _)| i).collect();
    idxs.sort();
    idxs.dedup();

    let rendered = render_line_set(
        &lines,
        frag_start_line0,
        &idxs,
        max_lines,
        cfg.ast_skeleton_max_line_chars,
        cfg,
    );
    if rendered.trim().is_empty() {
        None
    } else {
        Some(rendered)
    }
}

fn render_line_set(
    lines: &[&str],
    frag_start_line0: u32,
    idxs: &[usize],
    max_lines: usize,
    max_chars: usize,
    cfg: &StrategyConfig,
) -> String {
    let mut out = String::new();
    let mut written = 0usize;

    let indent_size = cfg.placeholder_indent_spaces.max(1).min(16);
    let collapse_enabled = cfg.block_collapse_enabled;
    let collapse_min_gap = cfg.block_collapse_min_gap_lines.max(2);

    let gap_indent = |prev: &str, next: &str| -> String {
        let p = prev.trim_end();
        let n = next.trim_start();
        let ip = leading_ws(prev).to_string();
        let inext = leading_ws(next).to_string();
        if p.ends_with('{') && n.starts_with('}') {
            let mut s = String::new();
            s.push_str(&ip);
            s.push_str(&" ".repeat(indent_size));
            return s;
        }
        if inext.len() > ip.len() {
            inext
        } else {
            ip
        }
    };

    let closing_suffix = |line: &str| -> Option<String> {
        let mut s = line.trim_start();
        if let Some((before, _comment)) = s.split_once("//") {
            s = before;
        }
        let s = s.trim_end();
        if s.starts_with('}') {
            Some(s.to_string())
        } else {
            None
        }
    };

    let can_collapse_block = |open_line: &str, close_line: &str| -> bool {
        let open_t = open_line.trim_end();
        if !open_t.ends_with('{') {
            return false;
        }
        if closing_suffix(close_line).is_none() {
            return false;
        }
        // Require matching indentation so we don't accidentally collapse across nested blocks.
        leading_ws(open_line).len() == leading_ws(close_line).len()
    };

    let collapse_line = |open_line: &str, close_line: &str| -> String {
        let open_t = open_line.trim_end();
        let before = open_t.strip_suffix('{').unwrap_or(open_t);
        let suffix = closing_suffix(close_line).unwrap_or("}".to_string());
        let collapsed = format!("{}{{ ... {}", before, suffix);
        truncate_line(&collapsed, max_chars)
    };

    let mut pos = 0usize;
    while pos < idxs.len() {
        if written >= max_lines {
            break;
        }

        let i = idxs[pos];
        let next = if pos + 1 < idxs.len() {
            Some(idxs[pos + 1])
        } else {
            None
        };

        // Block-aware collapsing: if we have `{` ... `}` with a large omitted region, compress to `{ ... }`.
        if collapse_enabled {
            if let Some(j) = next {
                if j > i.saturating_add(1) {
                    let omitted = j.saturating_sub(i).saturating_sub(1);
                    if omitted >= collapse_min_gap {
                        let open_line = lines.get(i).copied().unwrap_or("");
                        let close_line = lines.get(j).copied().unwrap_or("");
                        if can_collapse_block(open_line, close_line) {
                            let file_line_1based = frag_start_line0 as usize + i + 1;
                            let line = collapse_line(open_line, close_line);
                            out.push_str(&format!("L{:>5}: {}\n", file_line_1based, line));
                            written += 1;
                            pos += 2;
                            continue;
                        }
                    }
                }
            }
        }

        // Normal line
        let file_line_1based = frag_start_line0 as usize + i + 1;
        let line = truncate_line(lines.get(i).copied().unwrap_or(""), max_chars);
        out.push_str(&format!("L{:>5}: {}\n", file_line_1based, line));
        written += 1;

        // Gap placeholder
        if let Some(j) = next {
            if written >= max_lines {
                break;
            }
            if j > i.saturating_add(1) {
                let open_line = lines.get(i).copied().unwrap_or("");
                let close_line = lines.get(j).copied().unwrap_or("");
                let ind = gap_indent(open_line, close_line);
                out.push_str(&format!("{}...\n", ind));
                written += 1;
            }
        }

        pos += 1;
    }

    out
}

fn truncate_line(s: &str, max_chars: usize) -> String {
    if max_chars == 0 {
        return s.to_string();
    }
    // Cheap char-count truncate (avoid breaking UTF-8).
    if s.chars().count() <= max_chars {
        return s.to_string();
    }
    let mut out = String::new();
    let keep = max_chars.saturating_sub(3).max(1);
    for (i, ch) in s.chars().enumerate() {
        if i >= keep {
            break;
        }
        out.push(ch);
    }
    out.push_str("...");
    out
}

fn find_first_kind<'a>(mut node: Node<'a>, kind: &str) -> Option<Node<'a>> {
    if node.kind() == kind {
        return Some(node);
    }
    let mut cursor = node.walk();
    for ch in node.named_children(&mut cursor) {
        if let Some(n) = find_first_kind(ch, kind) {
            return Some(n);
        }
    }
    None
}

fn collect_skeleton_token_picks(
    bytes: &[u8],
    focus: &HashSet<String>,
    node: Node,
    _cursor: &mut tree_sitter::TreeCursor,
    add_line: &mut impl FnMut(usize, u16),
    added: &mut usize,
    line_cap: usize,
) {
    if *added >= 24 {
        return;
    }

    let kind = node.kind();
    if matches!(
        kind,
        "identifier"
            | "type_identifier"
            | "field_identifier"
            | "scoped_identifier"
            | "scoped_type_identifier"
    ) {
        if let Ok(t) = node.utf8_text(bytes) {
            let key = t.trim().to_ascii_lowercase();
            if !key.is_empty() && focus.contains(&key) {
                let stmt = statement_container(node);
                let (s, e) = node_line_span(&stmt, line_cap);
                add_line(s, 210);
                add_line(e, 200);
                add_line(node.start_position().row as usize, 220);
                *added += 1;
                if *added >= 24 {
                    return;
                }
            }
        }
    }

    if node.child_count() == 0 {
        return;
    }
    let mut c = node.walk();
    for ch in node.named_children(&mut c) {
        collect_skeleton_token_picks(bytes, focus, ch, _cursor, add_line, added, line_cap);
        if *added >= 24 {
            return;
        }
    }
}

fn collect_impl_method_skeleton_lines_rec(
    node: Node,
    add_line: &mut impl FnMut(usize, u16),
    limit: usize,
    n: &mut usize,
) {
    if *n >= limit {
        return;
    }
    if node.kind() == "function_item" && node.parent().map(|p| p.kind()) == Some("declaration_list")
    {
        let start = node.start_position().row as usize;
        add_line(start, 150);
        *n += 1;
        if *n >= limit {
            return;
        }
    }

    if node.child_count() == 0 {
        return;
    }
    let mut c = node.walk();
    for ch in node.named_children(&mut c) {
        collect_impl_method_skeleton_lines_rec(ch, add_line, limit, n);
        if *n >= limit {
            return;
        }
    }
}

fn collect_large_literal_skeleton_lines(
    node: &Node,
    depth: usize,
    cfg: &StrategyConfig,
    add_line: &mut impl FnMut(usize, u16),
    budget: &mut usize,
    line_cap: usize,
) {
    if *budget >= 8 {
        return;
    }
    if depth > cfg.ast_skeleton_max_depth {
        return;
    }

    if node.kind() == "array_expression" {
        let (s, e) = node_line_span(node, line_cap);
        let line_span = e.saturating_sub(s).saturating_add(1);
        let elem_count = node.named_child_count() as usize;
        let is_large = line_span >= cfg.ast_skeleton_large_literal_line_threshold
            || elem_count >= cfg.ast_skeleton_large_literal_elem_threshold;

        if is_large {
            add_line(s, 170);
            add_line(e, 160);
            let head = cfg.ast_skeleton_large_literal_head_lines.min(8);
            for i in 1..=head {
                let idx = s.saturating_add(i);
                if idx < e {
                    add_line(idx, 155);
                }
            }
            *budget += 1;
        }
    }

    let mut cursor = node.walk();
    for ch in node.named_children(&mut cursor) {
        collect_large_literal_skeleton_lines(&ch, depth + 1, cfg, add_line, budget, line_cap);
        if *budget >= 8 {
            return;
        }
    }
}

fn collect_control_flow_skeleton_lines(
    node: &Node,
    depth: usize,
    cfg: &StrategyConfig,
    add_line: &mut impl FnMut(usize, u16),
    budget: &mut usize,
    line_cap: usize,
) {
    if *budget == 0 {
        return;
    }
    if depth > cfg.ast_skeleton_max_depth {
        return;
    }

    match node.kind() {
        "match_expression" => {
            let (s, e) = node_line_span(node, line_cap);
            add_line(s, 120);
            add_line(e, 110);

            // Match arms (bounded).
            let mut arm_n = 0usize;
            let mut cursor = node.walk();
            for ch in node.named_children(&mut cursor) {
                if ch.kind() == "match_arm" {
                    let ls = ch.start_position().row as usize;
                    add_line(ls, 105);
                    arm_n += 1;
                    if arm_n >= cfg.ast_skeleton_match_arm_limit.max(1) {
                        break;
                    }
                }
            }

            *budget = budget.saturating_sub(1);
        }
        "if_expression" | "for_expression" | "while_expression" | "loop_expression" => {
            let (s, e) = node_line_span(node, line_cap);
            add_line(s, 80);
            if e > s {
                add_line(e, 70);
            }
            *budget = budget.saturating_sub(1);
        }
        _ => {}
    }

    let mut cursor = node.walk();
    for ch in node.named_children(&mut cursor) {
        collect_control_flow_skeleton_lines(&ch, depth + 1, cfg, add_line, budget, line_cap);
        if *budget == 0 {
            return;
        }
    }
}

fn statement_for_line<'a>(root: &Node<'a>, line0: usize) -> Option<Node<'a>> {
    use tree_sitter::Point;
    let p = Point {
        row: line0,
        column: 0,
    };
    let n = root.named_descendant_for_point_range(p, p)?;
    Some(statement_container(n))
}

fn statement_container<'a>(mut n: Node<'a>) -> Node<'a> {
    while let Some(p) = n.parent() {
        let pk = p.kind();
        if pk == "block" || pk == "source_file" || pk == "declaration_list" {
            break;
        }
        n = p;
    }
    n
}

fn node_line_span(n: &Node, max_lines: usize) -> (usize, usize) {
    let mut s = n.start_position().row as usize;
    let mut e = n.end_position().row as usize;
    let end_col = n.end_position().column;
    if end_col == 0 && e > s {
        e = e.saturating_sub(1);
    }
    s = s.min(max_lines.saturating_sub(1));
    e = e.min(max_lines.saturating_sub(1));
    if e < s {
        e = s;
    }
    (s, e)
}

fn push_windows_for_match(
    wins: &mut Vec<Win>,
    stmt: &Node,
    match_line: usize,
    ctx: usize,
    max_lines: usize,
) {
    let (s, e) = node_line_span(stmt, max_lines);
    // Header window: statement start + 1 line (helps for `if`/`match` headers).
    let header_end = (s.saturating_add(1)).min(e);
    wins.push(Win {
        start: s,
        end: header_end,
    });

    // Focus window around the match line, clamped to the statement span.
    let m = match_line.min(e).max(s);
    let a = m.saturating_sub(ctx).max(s);
    let b = m.saturating_add(ctx).min(e);
    wins.push(Win { start: a, end: b });
}

fn collect_token_windows(
    bytes: &[u8],
    focus: &HashSet<String>,
    node: Node,
    cursor: &mut tree_sitter::TreeCursor,
    wins: &mut Vec<Win>,
    ctx: usize,
    max_lines: usize,
    added: &mut usize,
) {
    // Limit windows to avoid pathological blowups.
    if *added >= 24 {
        return;
    }

    let kind = node.kind();
    if matches!(
        kind,
        "identifier"
            | "type_identifier"
            | "field_identifier"
            | "scoped_identifier"
            | "scoped_type_identifier"
    ) {
        if let Ok(t) = node.utf8_text(bytes) {
            let tl = t.trim();
            if !tl.is_empty() {
                let key = tl.to_ascii_lowercase();
                if focus.contains(&key) {
                    let stmt = statement_container(node);
                    let match_line = node.start_position().row as usize;
                    push_windows_for_match(wins, &stmt, match_line, ctx, max_lines);
                    *added += 1;
                    if *added >= 24 {
                        return;
                    }
                }
            }
        }
    }

    if node.child_count() == 0 {
        return;
    }
    let mut c = node.walk();
    for ch in node.named_children(&mut c) {
        collect_token_windows(bytes, focus, ch, cursor, wins, ctx, max_lines, added);
        if *added >= 24 {
            return;
        }
    }
}
